# Generated by Django 5.1.7 on 2025-03-23 19:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Character",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female"), ("O", "Other")],
                        max_length=1,
                    ),
                ),
                ("age", models.PositiveIntegerField()),
                ("skin", models.CharField(max_length=50)),
                (
                    "ethnicity",
                    models.CharField(
                        choices=[
                            ("CA", "Caucasian"),
                            ("AA", "African American"),
                            ("HI", "Hispanic"),
                            ("AS", "Asian"),
                            ("OT", "Other"),
                        ],
                        max_length=2,
                    ),
                ),
                (
                    "eye_color",
                    models.CharField(
                        choices=[
                            ("BR", "Brown"),
                            ("BL", "Blue"),
                            ("GR", "Green"),
                            ("HA", "Hazel"),
                            ("OT", "Other"),
                        ],
                        max_length=2,
                    ),
                ),
                (
                    "hair_color",
                    models.CharField(
                        choices=[
                            ("BK", "Black"),
                            ("BR", "Brown"),
                            ("BL", "Blonde"),
                            ("RD", "Red"),
                            ("OT", "Other"),
                        ],
                        max_length=2,
                    ),
                ),
                (
                    "hair_style",
                    models.CharField(
                        choices=[
                            ("SH", "Short"),
                            ("MD", "Medium"),
                            ("LG", "Long"),
                            ("BD", "Bald"),
                            ("OT", "Other"),
                        ],
                        max_length=2,
                    ),
                ),
                ("clothing", models.CharField(max_length=255)),
                (
                    "clothing_style",
                    models.CharField(
                        choices=[
                            ("CA", "Casual"),
                            ("FO", "Formal"),
                            ("SP", "Sporty"),
                            ("OT", "Other"),
                        ],
                        max_length=2,
                    ),
                ),
                ("accessories", models.JSONField()),
                ("expression", models.CharField(max_length=255)),
                ("pose", models.CharField(max_length=255)),
                (
                    "lighting",
                    models.CharField(
                        choices=[
                            ("SD", "Soft and Diffuse"),
                            ("HR", "Harsh"),
                            ("DR", "Dramatic"),
                            ("NT", "Natural"),
                            ("OT", "Other"),
                        ],
                        max_length=2,
                    ),
                ),
                ("additional_details", models.TextField()),
                (
                    "image_type",
                    models.CharField(
                        choices=[
                            ("PR", "Photorealistic"),
                            ("CT", "Cartoon"),
                            ("SK", "Sketch"),
                            ("OT", "Other"),
                        ],
                        max_length=2,
                    ),
                ),
                (
                    "style",
                    models.CharField(
                        choices=[
                            ("RL", "Realistic"),
                            ("CT", "Cartoonish"),
                            ("AB", "Abstract"),
                            ("OT", "Other"),
                        ],
                        max_length=2,
                    ),
                ),
                (
                    "texture",
                    models.CharField(
                        choices=[
                            ("SM", "Smooth"),
                            ("RF", "Rough"),
                            ("GR", "Grainy"),
                            ("OT", "Other"),
                        ],
                        max_length=2,
                    ),
                ),
                ("dominant_colors", models.CharField(max_length=50)),
                (
                    "contrast",
                    models.CharField(
                        choices=[("HI", "High"), ("MD", "Moderate"), ("LO", "Low")],
                        max_length=2,
                    ),
                ),
                (
                    "shading",
                    models.CharField(
                        choices=[("SF", "Soft"), ("HR", "Harsh"), ("NO", "None")],
                        max_length=2,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="characters",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Character",
                "verbose_name_plural": "Characters",
                "db_table": "characters",
            },
        ),
    ]
