# Generated by Django 5.1.7 on 2025-03-23 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("characters", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="character",
            name="image_url",
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
    ]
